apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: abuse-role
  namespace: default 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: default
  kind: ServiceAccount
  name: default
