---
username: mondoo
password: mondoo.com
domain_name: mondoo.hacklab
man_adcs_winrm_domain: '{{ domain_name }}'
domain_admin: Administrator
domain_admin_password: MondooSPM1!
netbios_name: MONDOO
domain_mode: WinThreshold
dns_server:
  - 10.0.4.10
  - 8.8.8.8
exchange_folder: C:\exchange2016
exchange_iso: C:\Tools\ExchangeServer2016-x64-cu12.iso
exchange_url: https://download.microsoft.com/download/2/5/8/258D30CF-CA4C-433A-A618-FB7E6BCC4EEE/ExchangeServer2016-x64-cu12.iso